services:
  apache:
    container_name: dreieichcon-apache
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/apache/laravel-proxy.conf:/usr/local/apache2/conf/extra/laravel-proxy.conf
    depends_on:
      - php
      - node
    networks:
      - internal

  node:
    container_name: dreieichcon-node
    image: node:lts
    working_dir: /var/www
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php
    networks:
      - internal
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www

  php:
    container_name: dreieichcon-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
    
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html

  mysql:
    container_name: dreieichcon-db
    image: mysql:latest
    platform: linux/x86_64
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dreieichcon_docker'
      MYSQL_USER: 'dreieichcon_docker'
      MYSQL_PASSWORD: 'dreieichcon_docker'
    volumes:
      - ./docker/db-data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge